### ISSUE TITLE
Settings lost after reboot : Error write config Os

### ISSUE THREAD

**Issue by Shaneosaure** [phush0/razer-laptop-control-no-dkms#6]
Hi, I've recently moved from the repo of [rdn-ash (razer-laptop-control)](https://github.com/rnd-ash/razer-laptop-control/issues) and i uninstalled it all for this repo.

**Issue :**
Everytime that i restart my computer, all the configuration i made like effects, logo and brigthness are lost.
When i check the daemon journal i have the following:

```shell
 ● razerdaemon.service - Razer laptop control daemon
     Loaded: loaded (/usr/lib/systemd/user/razerdaemon.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-06-28 09:36:38 CEST; 19min ago
   Main PID: 2116 (daemon)
      Tasks: 5 (limit: 18332)
     Memory: 1.8M
        CPU: 11.025s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/razerdaemon.service
             └─2116 /usr/share/razercontrol/daemon

juin 28 09:36:38 cyberdumb daemon[2116]: No effects save, creating a new one
juin 28 09:38:38 cyberdumb daemon[2116]: battery percentage: 97.0
juin 28 09:42:38 cyberdumb daemon[2116]: battery percentage: 96.0
juin 28 09:46:38 cyberdumb daemon[2116]: battery percentage: 95.0
juin 28 09:47:57 cyberdumb daemon[2116]: REQ: SetBrightness { ac: 0, val: 30 }
juin 28 09:47:57 cyberdumb daemon[2116]: Error write config Os { code: 2, kind: NotFound, message: "No such file or directory" }
juin 28 09:47:57 cyberdumb daemon[2116]: REQ: GetBrightness { ac: 0 }
juin 28 09:48:04 cyberdumb daemon[2116]: REQ: SetEffect { name: "static", params: [255, 255, 255] }
juin 28 09:50:38 cyberdumb daemon[2116]: battery percentage: 94.0
juin 28 09:54:38 cyberdumb daemon[2116]: battery percentage: 93.0

```

the following 
` Error write config Os { code: 2, kind: NotFound, message: "No such file or directory" }` 

**Additional info**

I had two issues previously which were solved by the help of other issues requests:

* Hidapi error,, which was solved using [this](https://github.com/phush0/razer-laptop-control-no-dkms/issues/5#issuecomment-1159458708)
* HIdapri permission denied error : solved with [this](https://github.com/phush0/razer-laptop-control-no-dkms/issues/3#issuecomment-1165892307)

I hope none of this is interfering with the current issue that i have ^^"

**Laptop Version**

I am using a Razer Blade 14" (2021) | RZ09-0370x on Pop!OS 22.04

Let me know if you need other info to help troubleshoot !

**Comment by JuanferM** [comment]
Hi, can you check if the directories `~/.local/share/razercontrol` and `/usr/local/share/razercontrol` exist?

The effects settings are stored in a _effects.json_ file in these directories. If these directories don't exist then the deamon will not be able to store your settings.

You can try creating the directories manually if they don't exist and then run the razer-cli commands that you want (if the directories exist the deamon should be able to create a save).

Regards,

**Comment by JuanferM** [comment]
@shashanknimje Glad to hear that!

 I also runned into an issue where the fan settings were lost after reboot and for anyone experiencing the same problem I might have found a solution. 
 
 The deamon's source code is in the `daemon.rs` file found in the `src` directory of this repo. In `daemon.rs` line 60, the instruction `d.set_ac_state(online);` seems to set the fan speed to 0 (automatic mode) by default. Changing that instruction to `d.set_ac_state_get();` and reinstalling the deamon with the `install.sh` script seems to keep the fan speed settings after reboot (it might be helpful to delete the `/usr/share/razercontrol` as the deamon could still be running). The effects can be reloaded after reboot thanks to lines 61 to 71 in `deamon.rs` but it seems that for fan speed the function used by default (`set_ac_state`) doesn't reload user settings.
 
 The functions `set_ac_state()` and `set_ac_state_get()` are implemented in the file `device.rs` and the code indicates that `set_ac_state_get()` reads the settings from the file `daemon.json` in the `~/.local/share/razercontrol` and the `/usr/share/razercontrol` directories.
 
**Keep in mind that my solution is more of a workaround and I advise to wait for @phush0 take on this before trying my solution since he is the developer of the deamon.**

**Comment by Shaneosaure** [comment]
> Hi, can you check if the directories `~/.local/share/razercontrol` and `/usr/share/razercontrol` exist?

> You can try creating the directories manually if they don't exist and then run the razer-cli commands that you want (if the directories exist the deamon should be able to create a save).

Thank you ! That was exactly the issue, apparently the dir  `~/.local/share/razercontrol` wasn't created. But now everything solved !
